Learning Outcomes
================

The learning outcomes of this session are

-   to have an introductory understanding of Jupyter notebooks.

-   To have an introductory understanding of the library NumPy,
    particularly with respect to vectors.

-   To examine a case where vectors can be analysed that have a much
    larger dimension than 3.

Notebooks
=========

If you haven’t encountered this before this is an example of a notebook
(specifically a Jupyter notebook). This brings together text and code
into one place.

The parts of this screen which have "In \[ \]:" to the left are referred
to as cells. Cells are pieces of code that can be run. You can run the
cells by clicking on the cell and pressing Control + Enter.

If the cell generates output it will appear immediately after the cell
in question when you do this.

Do not just click through all the cells without thinking about what each
cell is going to do.

**There will be cells that are empty - you will need to fill them!**

It’s important to note that the cells are in order and you should enter
them in that order.

For this section, you will be largely running things interactively but
it’s best to set up an editor window, type in there and then run the
script (The F5 key will very much be your friend here).

If you click on Help and Keyboard Shortcuts you will get a list of
shortcuts for doing particular operations (I find the one for creating a
cell below the one you are using is very useful).

If you want to save your notebook you can click on the diskette icon but
remember that if you restart your binder session the information will be
lost. To keep a permanent version on your machine, click on File and
then Download as and then Notebook. When you restart your binder session
on the directory page select Upload and then upload your file. You can
then run it from there.

You can also use <a href="https://colab.research.google.com/" class="uri">Google Colab</a> for this exercise. You will need to use the tab on 
the left hand side to load the data files which you can download from the github repo.

You can run Jupyter directly from the department server, (download the repository and type jupyter notebook from the command line). 

Finally, you can also run Jupyter from your own computer. Instructions on
this can be found at
<a href="https://jupyter.org/install" class="uri">https://jupyter.org/install</a>. If you do not have it you, 
<a href="https://docs.anaconda.com/anaconda/install/" class="uri"> anaconda </a> is a handy tool to download Python and Jupyter in one bundle.

In [1]:
# RUN ME FIRST!
from okgrade import grade

NumPy Introduction
==================

We will make use of NumPy for this course to work with vectors and
matrices. It’s worth keeping an eye on the QuickStart tutorial to NumPy
(which we copy from a great deal here)

<a href="https://docs.scipy.org/doc/numpy/user/" class="uri">https://docs.scipy.org/doc/numpy/user/</a>

and the NumPy manual at

<a href="https://docs.scipy.org/doc/numpy/index.html" class="uri">https://docs.scipy.org/doc/numpy/index.html</a>
.

The following will import this library into your session

In [2]:
import numpy as np

Grader Introduction
==================

In each notebook there are a series of *code cells* underneath every checkpoint which will run tests on your solutions. You should run them and move onto the next checkpoint. Run the following code below:

In [3]:
grade('tests/import.ok')

You should have gotten an output that looks something like this:

`Out[1]: tests/import.ok: All tests passed!`

It's possible that the tests will fail however and if that happens, hints will be given to you in the output of the test. For example, if you had not imported Numpy, you would expect to see something like this:

```
Test numpy-import 1 failed!

Test code:

            >>> # Numpy has not been imported!
		    >>> # Check that you have executed the 'import numpy as np' code cell!
                    >>>
		    >>> np is not None
                    True
```

The `>>>` indicates a Python prompt and the code that was run. **Hints will be given to you in the comments within these lines**, so make sure to read the errors.

If you did get the output above, then run the cell under the **Numpy Introduction** section before moving on.




# Numpy — Vectors

You can define a vector as follows:

In [4]:
a = np.array([1, 2, 3])

(Note the ordering of round and square brackets).

Inspect the contents of `a` by executing

In [5]:
a

array([1, 2, 3])

You can access individual components directly as you would like any
other array

In [6]:
a[0]

1

**CHECKPOINT 1: Define a variable 'a_2' and set it equal to the second entry in
`a`.**

In [7]:
a_2 = a[1]

In [8]:
grade('tests/cp1.ok')

The vector `a` has an associated set of methods including a nicer print
statement.

In [9]:
print(a)

[1 2 3]


The entries in `a` can be integers, floats and so on. Since Python is a
dynamically typed language, it tries to figure that out on the fly. One
can check the type as follows

In [10]:
a.dtype.name

'int64'

*Question* - what type did you get?

**CHECKPOINT 2: Create another vector `b`, [4, 5, 6], but where the entries are of type float.**

Hint: Refer to the Numpy documentation on how to specify the *dtype* of an array.

In [13]:
b = np.array([4., 5., 6.])

In [14]:
grade('tests/cp2.ok')

There is a transpose operation, but for vectors defined this way it
doesn’t really do anything. We’ll get back to this in the second lab.

In [15]:
a.T

array([1, 2, 3])

NumPy — Operations
==================

We define the following set of new vectors.

In [ ]:
c = np.array([1.,2.])

In [ ]:
d = np.array([2.,1.])

We can do many of the simple operations such as multiplication by a
scalar, adding and subtracting vectors. **Ask yourself what the output
should be before pressing enter.**

Type

In [ ]:
2. * c

In [ ]:
-.123 * d

In [ ]:
c + d

In [ ]:
c - d

As these vectors are objects, one needs to be careful when copying them
as using $=$ only passes the reference.

Type

In [ ]:
u = c

In [ ]:
print(u)

In [ ]:
c *= 3

In [ ]:
print(u)

If you use the `copy` method then the values of the vector are copied
across.

Type

In [ ]:
u = c.copy()

In [ ]:
print(u)

In [ ]:
c *= 3

**What will `u` look like now?**

In [ ]:
print(u)

One can compute the dot product between any two vectors. Type

In [ ]:
c = np.array([1.,2.])

In [ ]:
c.dot(d)

**CHECKPOINT Create a new vector that is orthogonal to `c`. Demonstrate
numerically that it is orthogonal.**

There isn’t a length function in NumPy but you can easily construct one.

Type

In [ ]:
import math

In [ ]:
math.sqrt(d.dot(d))

**CHECKPOINT Write a short function to compute the length of a vector.**

One can determine a unit vector `du` for a vector `d`.

Type

In [ ]:
du=d/math.sqrt(d.dot(d))

**CHECKPOINT Write a short function to compute the unit vector that is
parallel with an inputted vector. Do a check to make sure that vector
inputted is not the Null vector. Use that function to check that the new vector is a unit vector.** 

Higher dimensional example - character frequencies in different languages.
==========================================================================

If you are given a piece of text, then it is possible to compute the
frequency of occurence of each of the lower case letters in that text.
It turns out that the frequency of these letters is relatively fixed
from language to language (although this should not seen as an
absolutely fixed set of frequencies as every text can represent a
different style). It turns out that these frequencies are surprisingly
constant between different texts taken from the same language. We can
even use it to decrypt texts.

Put more mathematically for each text $\mathcal T$ we can compute the
frequency of each letter $f_a^{\mathcal T}$, $f_b^{\mathcal T}$ ,
$\dots$ where $f_a^{\mathcal T}$ is the frequency of lower case “a”’s in
$\mathcal T$ and so on. For the English alphabet there are 26 letters,
so we can construct a vector $\underline{f}^{\mathcal T}$ of those
frequencies. So, $\underline{f}^{\mathcal T}$ is a vector *with 26
entries*.

We can then compare how similar two texts $A$ and $B$ are by comparing
their frequencies. Let’s suppose that their corresponding frequency
vectors are $\underline{f}^A$ and $\underline{f}^B$. We can easily
compute cosine of the angle between these two vectors by computing
$$\cos \theta \;\; = \;\; \frac{{\underline{f^A}^\intercal} \cdot {\underline{f^B}}}{|\underline{f^A}||\underline{f^B}|} \;\; .$$

Remember -

1.  if $\cos \theta = 1$ then $\underline{f}^A$ and $\underline{f}^B$
    are parallel to each other, which indicates their frequencies are
    very similar.

2.  It doesn’t matter about the number of dimensions, the above
    relationship still holds (not just for two or three dimensions).

We can test this in Python. To do this you will write Python code to
compute the frequency of letters for a text and then to compute the dot
product between different frequency vectors. Without looking at the
files one can check if texts are from the same language or not.

In the cell below are two functions that will read in a text and return
a string and another function which will return a vector with the
*incidence* of lower case letters (i.e. how many times the letter “a”
occurs and so on) in a string.

In [ ]:
import re

def getString(fn):
    f = open(fn,'r')
    myString = f.read()
    return myString.lower()

def getIncidence(string):
    letters = "abcdefghijklmnopqrstuvwxyz"
    Nc = len(letters)
    n = np.zeros(Nc,dtype=np.float64)
    i = 0
    for c in letters:
        x = re.findall(c,string)
        n[i] = len(x) * 1.0
        i += 1
    return n

**CHECKPOINT Write a function that will compute the frequency vector of
the text found in a text file. The input is the file name of the text
file name and the output is the frequency vector for that file. If
$\underline{n}$ is the vector of incidences then
$$f_i \;\; = \;\; \frac{n_i}{\sum_j n_j} \;\; .$$ If you look in the NumPy
documentation you will a function to compute the denominator of this.
*This is not the same as computing the unit vector - prove this to
yourself*.**

**CHECKPOINT Write a function to compute the cosine of the angle between
two text frequency vectors. You will need the `math` library.**

**CHECKPOINT In the Jupyter folder there are three files, Dutch.txt,
English.txt and unknown.txt. The first two files are the same text in
Dutch and English respectively. Compute the cosines between the
resulting frequency vectors of the three texts and try and determine the
language of the file unknown.txt.**

Extension work
==============

Rotation encryption is one of the oldest methods for encrypting
texts.[1] The idea is relatively simple. Each letter in a text is
exchanged with a letter that is a specific number down from it in the
alphabetical sequence. So with a encryption rotation with an offset of
one would exchange

`a` $\rightarrow$ `b`,

`b` $\rightarrow$ `c`,

$\dots$

`z` $\rightarrow$ `a`.

The cipher rotation with an offset of 13 (or ROT-13) would be `a`
$\rightarrow$ `n` and so on.

If ones knows the offset, then one can decrypt the text by either
performing the reverse transformation on the encrypted text or
equivalently apply the transformation with a new offset where the sum of
the offsets is 26 (the number of letters in the alphabet). So in the
first case if a text has an encryption rotation with a offset of 1
applied to it and is then followed by an encryption rotation of 25 we
end up with the same text. Two applications of ROT-13 likewise return
you to the same text.

This encryption method can be very easily broken using the letter
frequency method that was discussed in the last set of lab materials. In
particular, *the frequencies of the letters will remain the same,
regardless of how they are transformed*. Furthermore if you have a
reference text, which you know is from the same language as the
encrypted text, then you can compare the frequencies to determine what
was the offset was.

If one applies the encryption rotation algorithm with right offset on
the encrypted text then the cosine of the angle between the two
frequency vectors should be close to 1.

The following function takes a string and carries out a rotation of a
string.

[1] The fact that it’s sometimes called the “Caesar Cipher” gives you an
idea of how old it is!

In [ ]:
import sys

def rot(s,shift):
    result = ""
    numLetters = 26
    if ( shift < -(numLetters-1) or shift > (numLetters-1) ):
        print("Error in rot function - shift must be > -25 and < 25")
        sys.exit(-1)
    for v in s:
        o, c, upper = v, v.lower(), v.isupper()
        if c >= 'a' and c <= 'z':
            deltaO = ord(c) - ord('a')
            deltaN = (deltaO + shift) % numLetters
            c = chr(ord('a') + deltaN)
        c = c.upper() if upper else c
        result += c

    return result

**CHECKPOINT In the Jupyter folder there is a piece of English text
encrypted using this approach called Englishencrypt.txt Using the above
function try and decrypt the text just by comparing the cosine of the
frequency vectors between the rotated text and the reference English.txt
file.**